version: '3.7'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    container_name: inventar-app
    volumes:
      - ./:/usr/src/app
      - /tmp:/tmp
    ports:
      - 8002:8000
    environment:
      - ENVIRONMENT=dev
      - API_TOKEN=SECRET_TOKEN
      - MONGO_URL="mongodb://inventar:password123@inventar-mongo:27017/inventar"
  mongo:
    image: 'bitnami/mongodb:latest'
    container_name: inventar-mongo
    ports:
      - 27017:27017
    environment:
      - MONGODB_ROOT_PASSWORD=geheim
      - MONGO_INITDB_DATABASE=inventar
      - MONGODB_USERNAME=inventar
      - MONGODB_PASSWORD=password123
      - MONGODB_DATABASE=inventar
