FROM public.ecr.aws/bitnami/python:3.8

RUN addgroup --system app && adduser --system --group app --home /home/app

ENV PORT=8765
ENV HOME=/home/app
ENV APP_HOME=/home/app/web
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV ENVIRONMENT prod
ENV TESTING 0

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chown -R app:app $APP_HOME

USER app

CMD uvicorn app.main:app --host 0.0.0.0 --port $PORT
