GET http://localhost:8002/hello
Accept: application/json

###
GET http://localhost:8002/api/network-devices
Accept: application/json

###

GET http://localhost:8002/api/network-devices/device2%2et0n%2eeu/
Accept: application/json

###

POST http://localhost:8002/api/network-devices
Content-Type: application/json

{
  "fqdn": "devicXXXe1.t0n.eu",
  "model": "ios-xe",
  "version": "0.1"
}

###

POST http://localhost:8002/api/network-devices
Content-Type: application/json

{
  "fqdn": "device2.t0n.eu",
  "model": "ios-xr",
  "version": "0.1"
}
